### ISSUE TITLE
kmovw immediate not assembling

### ISSUE THREAD

**Issue by gwoltman** [Terraspace/UASM#56]
This code:

	kmovw	k1, 01010101b
	vblendmpd zmm0{k1}, zmm2, zmm1

assembles as:

        kmovw   k1, k0                                  ; 0000 _ C5 F8: 90. C8
        push    rbp                                     ; 0004 _ 55
        vblendmpd zmm0 {k1}, zmm2, zmm1                 ; 0005 _ 62 F2 ED 49: 65. C1

I'm not sure if immediate addressing is allowed here.  Either way the above is not correct.

**Comment by gwoltman** [comment]
More odd kmovw behavior:

	kmovw	k1, r15d
	vblendmpd zmm0{k1}, zmm2, zmm1
	kmovw	k1, r15w
	vblendmpd zmm0{k1}, zmm2, zmm1
	kmovw	k1, r15

assembles as:

        kmovq   k1, r15                                 ; 0005 _ C4 C1 FB: 92. CF
        vblendmpd zmm0 {k1}, zmm2, zmm1                 ; 000A _ 62 F2 ED 49: 65. C1
        kmovq   k1, unknown register k15                ; 0010 _ C4 C1 FB: 90. CF
        vblendmpd zmm0 {k1}, zmm2, zmm1                 ; 0015 _ 62 F2 ED 49: 65. C1
        kmovq   k1, unknown register k15                ; 001B _ C4 C1 FB: 90. CF

**Comment by john-terraspace** [comment]
We fixing these now.

 

The immediate one I don’t believe is a valid instruction, so we will add an error for that type.

The GPR ones below should be valid.

**Comment by john-terraspace** [comment]
Hi,

 

Please try this pre-release of 2.38 we believe we’ve covered all the issues:

 

Encoding anomalies around kmov.

We also found some issues with kand(N) derivatives which have been fixed.

Vsubpd issues fixed.

Issues around encodings with scatter/gather for both avx2 and avx512.

 

We discovered while investigating scatter/gather that the opcodes will generate a #UD if anyone one of DEST, VECTOR INDEX or MASK register is the same, so we’ve provided an error now for this as that would be a nasty bug to try and pickup while debugging.

 

We’ve also added errors for the kmov scenarios where an immediate is not allowed.

 

http://www.terraspace.co.uk/uasm.zip

 

(Contains uasm32 and uasm64)

 

Please let us know how this one goes, if all is well we will publish it as it’s passed on all our other testing.

 

Thanks!

John

**Comment by gwoltman** [comment]
kmovw  k1, 01010101b

is still not generating an error message

All other kmovw problems are fixed in 2.38 pre-release

**Comment by gwoltman** [comment]
Fixed in 2.38 pre-release #2
