### ISSUE TITLE
Uasm 2.40 mis-assembly

### ISSUE THREAD

**Issue by gwoltman** [Terraspace/UASM#66]
This
	`vmovupd	[rsi-96]{k7}, zmm0`		
assembles as this (according to objconv):
`; Note: Prefix bit or byte has no meaning in this context`
`        vmovupd zmmword ptr [rsi-60H*40H] {k7}, zmm0    ; 00A3 _ 62 B1 FD 4F: 11. 46, A0`

**Comment by john-terraspace** [comment]
This should be fixed in 2.45

**Comment by john-terraspace** [comment]
All encoding related issues should be solved in 2.46 now due to complete automated regression test-suite that runs with each build and combines the expected output from jwasm, asmc, nasm and uasm.

**Comment by gwoltman** [comment]
Not fixed.

`	vmovupd	[rsi-88]{k7}, zmm0		`

assembles as:

`        vmovupd zmmword ptr [rsi-58H*40H] {k7}, zmm0    ; 00A4 _ 62 F1 FD 4F: 11. 46, A8`

**Comment by john-terraspace** [comment]
Goodness, that’s not good.. that means this is failing in the regression tests from all the other assemblers too… Oh well, lets fix it and be the first then!

**Comment by gwoltman** [comment]
Hi John,

I'm happy to test, but I need uasm32.exe.

Regards,
George

**Comment by john-terraspace** [comment]
Ah, ok.. I’ll update both versions shortly for you and send the links.

**Comment by john-terraspace** [comment]
Hi,

 

Both version are on the site for testing :

 

www.terraspace.co.uk/uasm64.zip <http://www.terraspace.co.uk/uasm64.zip> 

www.terraspace.co.uk/uasm32.zip <http://www.terraspace.co.uk/uasm32.zip> 

 

Let me know how that goes.

 

Cheers

John

**Comment by gwoltman** [comment]
The test version does fix this problem
